#!/usr/bin/perl

use strict;
use warnings;

use Games::Impatience;

use Getopt::Long;

my $seed;
GetOptions(
    'seed=i' => \$seed,
) or die "Wrong options!";

if (!defined($seed))
{
    die "Please specify a seed using the --seed command line option.";
};

my $game = Games::Impatience->new(
    {
        seed => $seed,
    }
);

$game->play();

1;

